//! Extractable trait example (recommended approach)
//!
//! This example demonstrates the recommended approach using the Extractable
//! trait with ExtractHelper for automatic extraction of different types.
//!
//! Run with: cargo run --example render_extraction_trait

use std::collections::HashMap;

// ============================================================================
// Rendering Primitives
// ============================================================================

#[derive(Debug, Clone, PartialEq)]
pub enum Color {
    White,
    Red,
    Blue,
    Green,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Vec2 {
    pub x: f32,
    pub y: f32,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Primitive {
    Circle { position: Vec2, radius: f32, color: Color },
    Sprite { position: Vec2, sprite_id: String, team_color: Color },
    Rectangle { position: Vec2, width: f32, height: f32, color: Color },
}

// ============================================================================
// Core Traits
// ============================================================================

/// Trait for types that can be converted to rendering primitives
pub trait Renderable {
    fn to_primitive(&self) -> Primitive;
}

/// Trait for types that can extract renderables from their fields
pub trait Extractable {
    fn extract_renderables(&self) -> HashMap<String, Primitive>;
}

/// Helper trait for extracting renderables from different types
pub trait ExtractHelper {
    fn extract(&self, field_name: &str, prefix: &str, result: &mut HashMap<String, Primitive>);
}

// Default implementation for Renderable types
impl<T: Renderable> ExtractHelper for T {
    fn extract(&self, field_name: &str, prefix: &str, result: &mut HashMap<String, Primitive>) {
        let path = if prefix.is_empty() {
            field_name.to_string()
        } else {
            format!("{}.{}", prefix, field_name)
        };
        result.insert(path, self.to_primitive());
    }
}

// Special implementation for Vec<T> where T: Renderable
impl<T: Renderable> ExtractHelper for Vec<T> {
    fn extract(&self, field_name: &str, prefix: &str, result: &mut HashMap<String, Primitive>) {
        for (i, item) in self.iter().enumerate() {
            let path = if prefix.is_empty() {
                format!("{}[{}]", field_name, i)
            } else {
                format!("{}.{}[{}]", prefix, field_name, i)
            };
            result.insert(path, item.to_primitive());
        }
    }
}

// ============================================================================
// Game State
// ============================================================================

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Team {
    Red,
    Blue,
}

pub struct Ball {
    pub position: Vec2,
    pub velocity: Vec2,
    pub radius: f32,
}

impl Renderable for Ball {
    fn to_primitive(&self) -> Primitive {
        Primitive::Circle {
            position: self.position.clone(),
            radius: self.radius,
            color: Color::White,
        }
    }
}

pub struct Player {
    pub position: Vec2,
    pub team: Team,
    pub is_selected: bool,
}

impl Renderable for Player {
    fn to_primitive(&self) -> Primitive {
        let team_color = match self.team {
            Team::Red => Color::Red,
            Team::Blue => Color::Blue,
        };
        Primitive::Sprite {
            position: self.position.clone(),
            sprite_id: "player".to_string(),
            team_color,
        }
    }
}

pub struct Field {
    pub width: f32,
    pub height: f32,
}

impl Renderable for Field {
    fn to_primitive(&self) -> Primitive {
        Primitive::Rectangle {
            position: Vec2 { x: 0.0, y: 0.0 },
            width: self.width,
            height: self.height,
            color: Color::Green,
        }
    }
}

pub struct SoccerGame {
    pub field: Field,
    pub ball: Ball,
    pub players: Vec<Player>,
    pub score: [u32; 2],
}

// Implement Extractable for SoccerGame
// In production, this would be generated by #[derive(Extractable)]
impl Extractable for SoccerGame {
    fn extract_renderables(&self) -> HashMap<String, Primitive> {
        let mut result = HashMap::new();

        // Extract each marked field using ExtractHelper
        ExtractHelper::extract(&self.field, "field", "", &mut result);
        ExtractHelper::extract(&self.ball, "ball", "", &mut result);
        ExtractHelper::extract(&self.players, "players", "", &mut result);
        // Note: score is not extracted (not renderable)

        result
    }
}

// ============================================================================
// Example
// ============================================================================

fn main() {
    println!("=== Extractable Trait Example (Recommended) ===\n");

    // Create a game state
    let game = SoccerGame {
        field: Field {
            width: 100.0,
            height: 60.0,
        },
        ball: Ball {
            position: Vec2 { x: 50.0, y: 30.0 },
            velocity: Vec2 { x: 1.0, y: 0.5 },
            radius: 2.0,
        },
        players: vec![
            Player {
                position: Vec2 { x: 20.0, y: 30.0 },
                team: Team::Red,
                is_selected: false,
            },
            Player {
                position: Vec2 { x: 80.0, y: 30.0 },
                team: Team::Blue,
                is_selected: true,
            },
            Player {
                position: Vec2 { x: 50.0, y: 50.0 },
                team: Team::Red,
                is_selected: false,
            },
        ],
        score: [0, 0],
    };

    // Extract renderables using the Extractable trait
    let primitives = game.extract_renderables();

    // Display results
    println!("Extracted {} rendering primitives:\n", primitives.len());

    // Sort keys for consistent output
    let mut keys: Vec<_> = primitives.keys().collect();
    keys.sort();

    for path in keys {
        let primitive = &primitives[path];
        match primitive {
            Primitive::Circle { position, radius, color } => {
                println!("  {} -> Circle at ({:.1}, {:.1}) radius {:.1} color {:?}",
                         path, position.x, position.y, radius, color);
            }
            Primitive::Sprite { position, sprite_id, team_color } => {
                println!("  {} -> Sprite '{}' at ({:.1}, {:.1}) color {:?}",
                         path, sprite_id, position.x, position.y, team_color);
            }
            Primitive::Rectangle { position, width, height, color } => {
                println!("  {} -> Rectangle at ({:.1}, {:.1}) size {}x{} color {:?}",
                         path, position.x, position.y, width, height, color);
            }
        }
    }

    println!("\n✓ Trait-based extraction complete!");
    println!("\nPros:");
    println!("  - Clean separation of concerns");
    println!("  - ExtractHelper handles different types automatically");
    println!("  - Easy to extend with more collection types");
    println!("  - Can be automated with derive macro");
    println!("  - Zero runtime type detection overhead");
    println!("\nCons:");
    println!("  - More upfront trait design");
    println!("  - Still requires manual impl (without derive macro)");
    println!("\nRecommendation:");
    println!("  Use this approach + derive macro for production!");
}
