// Research: Auto-Extraction of Renderable Types
//
// This test demonstrates multiple approaches to extracting "renderable" types
// from a game state struct by walking the type tree.

use serde::{Serialize, Serializer};
use serde_derive::Serialize as DeriveSerialize;
use std::collections::HashMap;
use std::fmt;

// ============================================================================
// PRIMITIVE RENDERING TYPES
// ============================================================================

#[derive(Debug, Clone, PartialEq)]
pub enum Color {
    White,
    Red,
    Blue,
}

#[derive(Debug, Clone, PartialEq, DeriveSerialize)]
pub struct Vec2 {
    pub x: f32,
    pub y: f32,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Primitive {
    Circle { position: Vec2, radius: f32, color: Color },
    Sprite { position: Vec2, sprite_id: String, team_color: Color },
    Rectangle { position: Vec2, width: f32, height: f32, color: Color },
}

// ============================================================================
// RENDERABLE TRAIT
// ============================================================================

/// Trait for types that can be converted to rendering primitives
pub trait Renderable {
    fn to_primitive(&self) -> Primitive;
}

// ============================================================================
// EXTRACTABLE TRAIT (for derive macro approach)
// ============================================================================

/// Trait for types that can extract renderable primitives from their fields
pub trait Extractable {
    fn extract_renderables(&self) -> HashMap<String, Primitive>;
}

/// Helper trait for extracting renderables from different types
pub trait ExtractHelper {
    fn extract(&self, field_name: &str, prefix: &str, result: &mut HashMap<String, Primitive>);
}

// Default implementation for Renderable types
impl<T: Renderable> ExtractHelper for T {
    fn extract(&self, field_name: &str, prefix: &str, result: &mut HashMap<String, Primitive>) {
        let path = if prefix.is_empty() {
            field_name.to_string()
        } else {
            format!("{}.{}", prefix, field_name)
        };
        result.insert(path, self.to_primitive());
    }
}

// Special implementation for Vec<T> where T: Renderable
impl<T: Renderable> ExtractHelper for Vec<T> {
    fn extract(&self, field_name: &str, prefix: &str, result: &mut HashMap<String, Primitive>) {
        for (i, item) in self.iter().enumerate() {
            let path = if prefix.is_empty() {
                format!("{}[{}]", field_name, i)
            } else {
                format!("{}.{}[{}]", prefix, field_name, i)
            };
            result.insert(path, item.to_primitive());
        }
    }
}

// ============================================================================
// GAME STATE TYPES
// ============================================================================

#[derive(Debug, Clone, Copy, PartialEq, DeriveSerialize)]
pub enum Team {
    Red,
    Blue,
}

#[derive(DeriveSerialize, Clone)]
pub struct Ball {
    pub position: Vec2,
    pub velocity: Vec2,
    pub radius: f32,
}

impl Renderable for Ball {
    fn to_primitive(&self) -> Primitive {
        Primitive::Circle {
            position: self.position.clone(),
            radius: self.radius,
            color: Color::White,
        }
    }
}

#[derive(DeriveSerialize, Clone)]
pub struct Player {
    pub position: Vec2,
    pub team: Team,
    pub is_selected: bool,
}

impl Renderable for Player {
    fn to_primitive(&self) -> Primitive {
        let team_color = match self.team {
            Team::Red => Color::Red,
            Team::Blue => Color::Blue,
        };
        Primitive::Sprite {
            position: self.position.clone(),
            sprite_id: "player".to_string(),
            team_color,
        }
    }
}

#[derive(DeriveSerialize, Clone)]
pub struct Field {
    pub width: f32,
    pub height: f32,
}

impl Renderable for Field {
    fn to_primitive(&self) -> Primitive {
        Primitive::Rectangle {
            position: Vec2 { x: 0.0, y: 0.0 },
            width: self.width,
            height: self.height,
            color: Color::White,
        }
    }
}

#[derive(DeriveSerialize)]
pub struct SoccerGame {
    pub field: Field,
    pub ball: Ball,
    pub players: Vec<Player>,
    pub score: [u32; 2],
}

// Manual implementation of Extractable for SoccerGame
// (In real code, this would be generated by #[derive(Extractable)])
impl Extractable for SoccerGame {
    fn extract_renderables(&self) -> HashMap<String, Primitive> {
        let mut result = HashMap::new();
        
        // Extract field
        ExtractHelper::extract(&self.field, "field", "", &mut result);
        
        // Extract ball
        ExtractHelper::extract(&self.ball, "ball", "", &mut result);
        
        // Extract players (Vec implementation handles indices)
        ExtractHelper::extract(&self.players, "players", "", &mut result);
        
        result
    }
}

// ============================================================================
// APPROACH 1: CUSTOM SERIALIZER WITH PATH TRACKING
// ============================================================================

/// Custom serializer that extracts Renderable types while tracking paths
pub struct RenderExtractor {
    path: Vec<String>,
    extracted: HashMap<String, Primitive>,
}

impl RenderExtractor {
    pub fn new() -> Self {
        Self {
            path: Vec::new(),
            extracted: HashMap::new(),
        }
    }

    pub fn extract<T: Serialize>(value: &T) -> HashMap<String, Primitive> {
        let mut extractor = RenderExtractor::new();
        // We ignore the result since we're just walking the tree
        let _ = value.serialize(&mut extractor);
        extractor.extracted
    }

    fn current_path(&self) -> String {
        self.path.join(".")
    }

    fn push_path(&mut self, segment: String) {
        self.path.push(segment);
    }

    fn pop_path(&mut self) {
        self.path.pop();
    }

    // Helper to emit a primitive if we detect a Renderable type
    // This is called manually in test code since we can't do runtime type detection
    pub fn emit(&mut self, primitive: Primitive) {
        let path = self.current_path();
        self.extracted.insert(path, primitive);
    }
}

// Implement Serializer trait for RenderExtractor
impl<'a> Serializer for &'a mut RenderExtractor {
    type Ok = ();
    type Error = ExtractorError;

    type SerializeSeq = SeqSerializer<'a>;
    type SerializeTuple = TupleSerializer<'a>;
    type SerializeTupleStruct = TupleStructSerializer<'a>;
    type SerializeTupleVariant = TupleVariantSerializer<'a>;
    type SerializeMap = MapSerializer<'a>;
    type SerializeStruct = StructSerializer<'a>;
    type SerializeStructVariant = StructVariantSerializer<'a>;

    fn serialize_bool(self, _v: bool) -> Result<(), ExtractorError> {
        Ok(())
    }

    fn serialize_i8(self, _v: i8) -> Result<(), ExtractorError> {
        Ok(())
    }

    fn serialize_i16(self, _v: i16) -> Result<(), ExtractorError> {
        Ok(())
    }

    fn serialize_i32(self, _v: i32) -> Result<(), ExtractorError> {
        Ok(())
    }

    fn serialize_i64(self, _v: i64) -> Result<(), ExtractorError> {
        Ok(())
    }

    fn serialize_u8(self, _v: u8) -> Result<(), ExtractorError> {
        Ok(())
    }

    fn serialize_u16(self, _v: u16) -> Result<(), ExtractorError> {
        Ok(())
    }

    fn serialize_u32(self, _v: u32) -> Result<(), ExtractorError> {
        Ok(())
    }

    fn serialize_u64(self, _v: u64) -> Result<(), ExtractorError> {
        Ok(())
    }

    fn serialize_f32(self, _v: f32) -> Result<(), ExtractorError> {
        Ok(())
    }

    fn serialize_f64(self, _v: f64) -> Result<(), ExtractorError> {
        Ok(())
    }

    fn serialize_char(self, _v: char) -> Result<(), ExtractorError> {
        Ok(())
    }

    fn serialize_str(self, _v: &str) -> Result<(), ExtractorError> {
        Ok(())
    }

    fn serialize_bytes(self, _v: &[u8]) -> Result<(), ExtractorError> {
        Ok(())
    }

    fn serialize_none(self) -> Result<(), ExtractorError> {
        Ok(())
    }

    fn serialize_some<T: ?Sized>(self, value: &T) -> Result<(), ExtractorError>
    where
        T: Serialize,
    {
        value.serialize(self)
    }

    fn serialize_unit(self) -> Result<(), ExtractorError> {
        Ok(())
    }

    fn serialize_unit_struct(self, _name: &'static str) -> Result<(), ExtractorError> {
        Ok(())
    }

    fn serialize_unit_variant(
        self,
        _name: &'static str,
        _variant_index: u32,
        _variant: &'static str,
    ) -> Result<(), ExtractorError> {
        Ok(())
    }

    fn serialize_newtype_struct<T: ?Sized>(
        self,
        _name: &'static str,
        value: &T,
    ) -> Result<(), ExtractorError>
    where
        T: Serialize,
    {
        value.serialize(self)
    }

    fn serialize_newtype_variant<T: ?Sized>(
        self,
        _name: &'static str,
        _variant_index: u32,
        _variant: &'static str,
        value: &T,
    ) -> Result<(), ExtractorError>
    where
        T: Serialize,
    {
        value.serialize(self)
    }

    fn serialize_seq(self, _len: Option<usize>) -> Result<Self::SerializeSeq, ExtractorError> {
        Ok(SeqSerializer {
            extractor: self,
            index: 0,
        })
    }

    fn serialize_tuple(self, _len: usize) -> Result<Self::SerializeTuple, ExtractorError> {
        Ok(TupleSerializer {
            extractor: self,
            index: 0,
        })
    }

    fn serialize_tuple_struct(
        self,
        _name: &'static str,
        _len: usize,
    ) -> Result<Self::SerializeTupleStruct, ExtractorError> {
        Ok(TupleStructSerializer {
            extractor: self,
            index: 0,
        })
    }

    fn serialize_tuple_variant(
        self,
        _name: &'static str,
        _variant_index: u32,
        _variant: &'static str,
        _len: usize,
    ) -> Result<Self::SerializeTupleVariant, ExtractorError> {
        Ok(TupleVariantSerializer {
            extractor: self,
            index: 0,
        })
    }

    fn serialize_map(self, _len: Option<usize>) -> Result<Self::SerializeMap, ExtractorError> {
        Ok(MapSerializer {
            extractor: self,
            key: None,
        })
    }

    fn serialize_struct(
        self,
        _name: &'static str,
        _len: usize,
    ) -> Result<Self::SerializeStruct, ExtractorError> {
        Ok(StructSerializer { extractor: self })
    }

    fn serialize_struct_variant(
        self,
        _name: &'static str,
        _variant_index: u32,
        _variant: &'static str,
        _len: usize,
    ) -> Result<Self::SerializeStructVariant, ExtractorError> {
        Ok(StructVariantSerializer { extractor: self })
    }
}

// ============================================================================
// COMPOUND SERIALIZERS
// ============================================================================

pub struct SeqSerializer<'a> {
    extractor: &'a mut RenderExtractor,
    index: usize,
}

impl<'a> serde::ser::SerializeSeq for SeqSerializer<'a> {
    type Ok = ();
    type Error = ExtractorError;

    fn serialize_element<T: ?Sized>(&mut self, value: &T) -> Result<(), ExtractorError>
    where
        T: Serialize,
    {
        self.extractor.push_path(format!("[{}]", self.index));
        value.serialize(&mut *self.extractor)?;
        self.extractor.pop_path();
        self.index += 1;
        Ok(())
    }

    fn end(self) -> Result<(), ExtractorError> {
        Ok(())
    }
}

pub struct TupleSerializer<'a> {
    extractor: &'a mut RenderExtractor,
    index: usize,
}

impl<'a> serde::ser::SerializeTuple for TupleSerializer<'a> {
    type Ok = ();
    type Error = ExtractorError;

    fn serialize_element<T: ?Sized>(&mut self, value: &T) -> Result<(), ExtractorError>
    where
        T: Serialize,
    {
        self.extractor.push_path(format!("{}", self.index));
        value.serialize(&mut *self.extractor)?;
        self.extractor.pop_path();
        self.index += 1;
        Ok(())
    }

    fn end(self) -> Result<(), ExtractorError> {
        Ok(())
    }
}

pub struct TupleStructSerializer<'a> {
    extractor: &'a mut RenderExtractor,
    index: usize,
}

impl<'a> serde::ser::SerializeTupleStruct for TupleStructSerializer<'a> {
    type Ok = ();
    type Error = ExtractorError;

    fn serialize_field<T: ?Sized>(&mut self, value: &T) -> Result<(), ExtractorError>
    where
        T: Serialize,
    {
        self.extractor.push_path(format!("{}", self.index));
        value.serialize(&mut *self.extractor)?;
        self.extractor.pop_path();
        self.index += 1;
        Ok(())
    }

    fn end(self) -> Result<(), ExtractorError> {
        Ok(())
    }
}

pub struct TupleVariantSerializer<'a> {
    extractor: &'a mut RenderExtractor,
    index: usize,
}

impl<'a> serde::ser::SerializeTupleVariant for TupleVariantSerializer<'a> {
    type Ok = ();
    type Error = ExtractorError;

    fn serialize_field<T: ?Sized>(&mut self, value: &T) -> Result<(), ExtractorError>
    where
        T: Serialize,
    {
        self.extractor.push_path(format!("{}", self.index));
        value.serialize(&mut *self.extractor)?;
        self.extractor.pop_path();
        self.index += 1;
        Ok(())
    }

    fn end(self) -> Result<(), ExtractorError> {
        Ok(())
    }
}

pub struct MapSerializer<'a> {
    extractor: &'a mut RenderExtractor,
    key: Option<String>,
}

impl<'a> serde::ser::SerializeMap for MapSerializer<'a> {
    type Ok = ();
    type Error = ExtractorError;

    fn serialize_key<T: ?Sized>(&mut self, _key: &T) -> Result<(), ExtractorError>
    where
        T: Serialize,
    {
        // For simplicity, we don't format the key - just use a placeholder
        // In a real implementation, you'd serialize the key to a string
        self.key = Some("key".to_string());
        Ok(())
    }

    fn serialize_value<T: ?Sized>(&mut self, value: &T) -> Result<(), ExtractorError>
    where
        T: Serialize,
    {
        if let Some(key) = self.key.take() {
            self.extractor.push_path(key);
            value.serialize(&mut *self.extractor)?;
            self.extractor.pop_path();
        }
        Ok(())
    }

    fn end(self) -> Result<(), ExtractorError> {
        Ok(())
    }
}

pub struct StructSerializer<'a> {
    extractor: &'a mut RenderExtractor,
}

impl<'a> serde::ser::SerializeStruct for StructSerializer<'a> {
    type Ok = ();
    type Error = ExtractorError;

    fn serialize_field<T: ?Sized>(
        &mut self,
        key: &'static str,
        value: &T,
    ) -> Result<(), ExtractorError>
    where
        T: Serialize,
    {
        self.extractor.push_path(key.to_string());
        value.serialize(&mut *self.extractor)?;
        self.extractor.pop_path();
        Ok(())
    }

    fn end(self) -> Result<(), ExtractorError> {
        Ok(())
    }
}

pub struct StructVariantSerializer<'a> {
    extractor: &'a mut RenderExtractor,
}

impl<'a> serde::ser::SerializeStructVariant for StructVariantSerializer<'a> {
    type Ok = ();
    type Error = ExtractorError;

    fn serialize_field<T: ?Sized>(
        &mut self,
        key: &'static str,
        value: &T,
    ) -> Result<(), ExtractorError>
    where
        T: Serialize,
    {
        self.extractor.push_path(key.to_string());
        value.serialize(&mut *self.extractor)?;
        self.extractor.pop_path();
        Ok(())
    }

    fn end(self) -> Result<(), ExtractorError> {
        Ok(())
    }
}

// ============================================================================
// ERROR TYPE
// ============================================================================

#[derive(Debug)]
pub struct ExtractorError {
    msg: String,
}

impl fmt::Display for ExtractorError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "Extractor error: {}", self.msg)
    }
}

impl std::error::Error for ExtractorError {}

impl serde::ser::Error for ExtractorError {
    fn custom<T: fmt::Display>(msg: T) -> Self {
        ExtractorError {
            msg: msg.to_string(),
        }
    }
}

// ============================================================================
// APPROACH 2: WRAPPER TYPE WITH MANUAL EXTRACTION
// ============================================================================

/// Manual extraction approach - wraps a type and provides extraction
pub struct ExtractWrapper<T> {
    value: T,
    extractor: RenderExtractor,
}

impl<T> ExtractWrapper<T> {
    pub fn new(value: T) -> Self {
        Self {
            value,
            extractor: RenderExtractor::new(),
        }
    }

    pub fn extracted(&self) -> &HashMap<String, Primitive> {
        &self.extractor.extracted
    }
}

// We could implement custom extraction for specific types
impl ExtractWrapper<SoccerGame> {
    pub fn extract_renderables(mut self) -> HashMap<String, Primitive> {
        // Manually extract each renderable type
        self.extractor.path.push("field".to_string());
        self.extractor.emit(self.value.field.to_primitive());
        self.extractor.path.pop();

        self.extractor.path.push("ball".to_string());
        self.extractor.emit(self.value.ball.to_primitive());
        self.extractor.path.pop();

        for (i, player) in self.value.players.iter().enumerate() {
            self.extractor.path.push(format!("players[{}]", i));
            self.extractor.emit(player.to_primitive());
            self.extractor.path.pop();
        }

        self.extractor.extracted
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[test]
fn test_render_extractor_basics() {
    let mut extractor = RenderExtractor::new();
    
    // Manually test path tracking
    extractor.push_path("field".to_string());
    assert_eq!(extractor.current_path(), "field");
    
    extractor.push_path("width".to_string());
    assert_eq!(extractor.current_path(), "field.width");
    
    extractor.pop_path();
    assert_eq!(extractor.current_path(), "field");
    
    extractor.pop_path();
    assert_eq!(extractor.current_path(), "");
}

#[test]
fn test_manual_extraction_approach() {
    let game = SoccerGame {
        field: Field {
            width: 100.0,
            height: 60.0,
        },
        ball: Ball {
            position: Vec2 { x: 50.0, y: 30.0 },
            velocity: Vec2 { x: 1.0, y: 0.5 },
            radius: 2.0,
        },
        players: vec![
            Player {
                position: Vec2 { x: 20.0, y: 30.0 },
                team: Team::Red,
                is_selected: false,
            },
            Player {
                position: Vec2 { x: 80.0, y: 30.0 },
                team: Team::Blue,
                is_selected: true,
            },
        ],
        score: [0, 0],
    };

    let wrapper = ExtractWrapper::new(game);
    let extracted = wrapper.extract_renderables();

    // Verify we extracted the right primitives
    assert!(extracted.contains_key("field"));
    assert!(extracted.contains_key("ball"));
    assert!(extracted.contains_key("players[0]"));
    assert!(extracted.contains_key("players[1]"));

    // Check ball primitive
    if let Some(Primitive::Circle { position, radius, color }) = extracted.get("ball") {
        assert_eq!(position.x, 50.0);
        assert_eq!(position.y, 30.0);
        assert_eq!(*radius, 2.0);
        assert_eq!(*color, Color::White);
    } else {
        panic!("Ball primitive not found or wrong type");
    }

    // Check player primitives
    if let Some(Primitive::Sprite { position, team_color, .. }) = extracted.get("players[0]") {
        assert_eq!(position.x, 20.0);
        assert_eq!(*team_color, Color::Red);
    } else {
        panic!("Player 0 primitive not found or wrong type");
    }
}

#[test]
fn test_serializer_path_tracking() {
    // Create a simple game state
    let game = SoccerGame {
        field: Field {
            width: 100.0,
            height: 60.0,
        },
        ball: Ball {
            position: Vec2 { x: 50.0, y: 30.0 },
            velocity: Vec2 { x: 1.0, y: 0.5 },
            radius: 2.0,
        },
        players: vec![
            Player {
                position: Vec2 { x: 20.0, y: 30.0 },
                team: Team::Red,
                is_selected: false,
            },
        ],
        score: [1, 2],
    };

    // Use the custom serializer to walk the tree
    // Note: This won't extract automatically since Rust doesn't support
    // runtime type introspection, but it demonstrates the path tracking
    let mut extractor = RenderExtractor::new();
    let _ = game.serialize(&mut extractor);
    
    // The extractor successfully walked the tree without errors
    // In a real implementation, we'd need a way to detect Renderable types
}

#[test]
fn test_extractable_trait_approach() {
    // This demonstrates the recommended approach using the Extractable trait
    let game = SoccerGame {
        field: Field {
            width: 100.0,
            height: 60.0,
        },
        ball: Ball {
            position: Vec2 { x: 50.0, y: 30.0 },
            velocity: Vec2 { x: 1.0, y: 0.5 },
            radius: 2.0,
        },
        players: vec![
            Player {
                position: Vec2 { x: 20.0, y: 30.0 },
                team: Team::Red,
                is_selected: false,
            },
            Player {
                position: Vec2 { x: 80.0, y: 30.0 },
                team: Team::Blue,
                is_selected: true,
            },
        ],
        score: [0, 0],
    };

    // Extract using the Extractable trait
    let extracted = game.extract_renderables();

    // Verify extraction
    assert_eq!(extracted.len(), 4); // field, ball, players[0], players[1]
    assert!(extracted.contains_key("field"));
    assert!(extracted.contains_key("ball"));
    assert!(extracted.contains_key("players[0]"));
    assert!(extracted.contains_key("players[1]"));

    // Verify ball data
    if let Some(Primitive::Circle { position, radius, color }) = extracted.get("ball") {
        assert_eq!(position.x, 50.0);
        assert_eq!(position.y, 30.0);
        assert_eq!(*radius, 2.0);
        assert_eq!(*color, Color::White);
    } else {
        panic!("Ball primitive not extracted correctly");
    }

    // Verify players data
    if let Some(Primitive::Sprite { position, team_color, .. }) = extracted.get("players[0]") {
        assert_eq!(position.x, 20.0);
        assert_eq!(*team_color, Color::Red);
    } else {
        panic!("Player 0 primitive not extracted correctly");
    }

    if let Some(Primitive::Sprite { position, team_color, .. }) = extracted.get("players[1]") {
        assert_eq!(position.x, 80.0);
        assert_eq!(*team_color, Color::Blue);
    } else {
        panic!("Player 1 primitive not extracted correctly");
    }
}

// ============================================================================
// APPROACH 3: TYPE REGISTRY PATTERN (CONCEPTUAL)
// ============================================================================

// This approach demonstrates using a global type registry with crates like
// `inventory` or `linkme` to register Renderable types at compile time.
//
// The idea is:
// 1. Each Renderable type registers itself in a global registry
// 2. The custom serializer checks the registry by type name or TypeId
// 3. When a match is found, call the registered extraction function
//
// Pros:
// - Can work with serde's Serializer trait
// - Automatic registration via proc macro
//
// Cons:
// - Requires unsafe code for type erasure
// - Type name matching is fragile
// - Additional dependencies (inventory ~100KB)
// - More complex than recommended approach
//
// This is commented out because:
// - It's conceptual/educational
// - Requires external crates not in dependencies
// - Not the recommended approach (custom derive is simpler)

/*
use inventory;

pub struct RenderableTypeInfo {
    pub type_id: TypeId,
    pub extract_fn: fn(*const ()) -> Primitive,
}

inventory::collect!(RenderableTypeInfo);

// In the Ball implementation:
inventory::submit! {
    RenderableTypeInfo {
        type_id: TypeId::of::<Ball>(),
        extract_fn: |ptr| {
            let ball = unsafe { &*(ptr as *const Ball) };
            ball.to_primitive()
        }
    }
}

// Then in the serializer, check the registry by TypeId
*/

#[test]
fn test_type_info_concept() {
    // This test demonstrates that we can use TypeId in theory,
    // but we can't get TypeId from a Serialize trait alone
    use std::any::TypeId;
    
    let _ball = Ball {
        position: Vec2 { x: 10.0, y: 20.0 },
        velocity: Vec2 { x: 0.0, y: 0.0 },
        radius: 5.0,
    };
    
    // We can get TypeId from concrete types
    let type_id = TypeId::of::<Ball>();
    assert!(type_id == TypeId::of::<Ball>());
    
    // But we can't get TypeId from &dyn Serialize
    // This is the fundamental limitation
}

